name: Bitcoin Price Auto Commit

on:
  push:
    branches:
      - main
  schedule:
      - cron: '*/5 * * * *'
  workflow_dispatch: 

permissions:
  contents: write 

env:
  GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
  GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}

jobs:
  bitcoin-price:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git identity
        run: |
          git config user.email "$GIT_USER_EMAIL"
          git config user.name "$GIT_USER_NAME"

      - name: Fetch and merge latest changes
        run: |
          git fetch origin
          git merge --strategy-option=ours --allow-unrelated-histories origin/main || true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run app.py
        id: bitcoin
        run: |
          python app.py

      - name: Commit and push changes
        run: |
          git add -A
          COMMIT_MSG=$(cat output/bitcoin_price.txt)
          git commit -m "$COMMIT_MSG" || true
          git push origin HEAD:main --force
